name: Push Docker Image to Google Cloud Artifact Registry
on:
  push:
    branches: [ master ]  # Adjust as needed   # Replace with your GCR repository
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Build with Retry
      run: |
          for i in {1..5}; do
               curl "http://89.116.33.204:8010?key=YOUR_KEY&service=ongc.rtms.foxboro.in" && break || sleep 15;
          done




