name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Deploy, build, and clean up on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << EOF
          echo "Deploying the project"
          mkdir -p ~/work/Oscars
          cd ~/work/Oscars
          if [ -d ".git" ]; then
            git pull origin master
          else
            git clone https://github.com/Karan1980/RTMS-Frontend.git .
          fi
          npm install
          npm run build
          sudo rm -rf /var/www/foxboro/*
          sudo cp -r dist/* /var/www/foxboro/
          sudo rm -rf /var/www/ongc.foxboro/*
          sudo cp -r dist/* /var/www/ongc.rtms.foxboro/
          sudo systemctl restart nginx
          cd ~
          rm -rf ~/work/Oscars
          EOF
